### PR TITLE
add files limit, prohibit absolute paths

### PR DESCRIPTION
**Pull request by cmlsharp**

### CODE REVIEW

**Comment by Jelleas** [comment]
Some subtleties here! 

* `_glob` is also used for `!exclude`. That means if someone were to `!exclude *`, `lib50` would now error if there are more than 100 files excluded by that one globbing pattern.
* `push()`s `file_limit` actually affects how many files can be globbed by any globbing pattern. That means `!include *` could hit that limit, but `!include *.c` and `!include .h` could dodge it, even if only those file types are present. It's rather technical and non-sensical at that abstraction level. Even more so because it also affects excluded files...

But just to serve as a sensible default, this PR makes sense and addresses https://github.com/cs50/submit50/issues/239. In a realistic setting no one would randomly expect a submission or a check to run on that many files, even if they were all just excluded. Given that it also affects excluded globbing patterns I did raise the default to `10000`. That should be well above any sensible number of files, even for a `build` folder or such.

**Comment by Jelleas** [comment]
Ready to merge if you ask me!

**Comment by cmlsharp** [comment]
Your second point isn't quite true precisely because we begin with an implicit `!include "*"`. Hence, there's no way to cheat since `|c files| + |h files| < |all files|`. This is because we do not allow you to include files outside the current directory.

For a similar reason, removing the limit on `exclude` would do nothing. In this context it really is a `file_limit` on the number of files that can be considered for inclusion/exclusion.

**Comment by cmlsharp** [comment]
Also, I improved the absolute path checking to also disallow e.g. `!include "~/sensitive_info.txt"`and `!include "../sensitive_info.txt"`. There's no method that does this directly, but basically what I do is `resolve` each pattern and check if the resulting file would be in the current directory. 
 
 Technically, this would allow someone to specify an absolute path in an `!include`, but it would have to be one that refers to a file within the student's current directory, so there's no potential security issue.

**Comment by cmlsharp** [comment]
Oh, we also need to be careful about the error message in `files` now that I think of it. Remember, we also use `files` in `compare50`. If they had too many files inside a student submission (a highly degenerate case, granted)

```
"Looks like you are in a directory with too many (> 10000) files.").format(limit),
You are currently in: /home/chad/Documents/submissions/student471, did you perhaps intend another directory?
```
Maybe this isn't a huge issue, but this would be a bit of a confusing error message since they aren't actually cd'd into the `student471` folder.

**Comment by cmlsharp** [comment]
Alternatively, we can just catch this exception and raise a different message in `compare50` which probably makes sens.

**Comment by Jelleas** [comment]
We should realistically catch this error in every tool, even if just to formulate it in terms of that tool. But for now, not a rush for compare50, it's quite understandable even from this message alone.

But I do think this needs to be a command line option for compare50, and probably with a lower default (100?) too. I've seen fellow teachers mess up, and do something like `compare50 submissions`, which would be pretty easily caught this way.

**Comment by cmlsharp** [comment]
Yeah, true. I wonder if it would be overall helpful to, in the instance that you only specify one directory submission, have compare50 infer that you probably meant all the folders/files inside that submission?

Of course if you specify any archive submissions we wouldn't be able to make this assumption.

**Comment by Jelleas** [comment]
moving back to `file_limit` because of the implicit `!include`. A better name for something that is externally exposed imo

**Pull request merged**
