### PR TITLE
Auth warning

### PR DESCRIPTION
**Pull request by Jelleas**
Addressing: https://github.com/cs50/lib50/issues/72

This hides the warning in case SSH auth succeeds right away (without a passphrase).

### CODE REVIEW

**Comment by dmalan** [comment]
@rongxin-liu mind trying out before deploying to cluster?

**Comment by dmalan** [comment]
Thanks, @Jelleas!

**Comment by rongxin-liu** [comment]
Thanks! I just ran some tests and realized there might be two cases that lib50 will still prompt that message:

1. When GitHub SSH server is not in the known_host (first-time student finishes setting up SSH)
2. When the student is using a passphrase protected SSH key

Maybe we can prompt the warning whenever lib50 uses https authentication instead? That way, we might not need to consider each corner case when SSH authentication failed.

**Comment by Jelleas** [comment]
@rongxin-liu 

1. Good catch! Moving the warning till after that is checked and fixed should do it.
2. This is intentional. I do believe showing this warning before a passphrase prompt can help avoid some confusion. Realistically this targets just the group of people that have at some point setup SSH with a passphrase prior to all this, and now find `check50` suddenly prompting for that passphrase. Arguably a small group but at this scale who knows ;)

Latest commit now prompts iff a passphrase is prompted or on https auth.

**Comment by rongxin-liu** [comment]
> @rongxin-liu
> 
> 1. Good catch! Moving the warning till after that is checked and fixed should do it.
> 2. This is intentional. I do believe showing this warning before a passphrase prompt can help avoid some confusion. Realistically this targets just the group of people that have at some point setup SSH with a passphrase prior to all this, and now find `check50` suddenly prompting for that passphrase. Arguably a small group but at this scale who knows ;)
> 
> Latest commit now prompts iff a passphrase is prompted or on https auth.

Ah, got it!

Right now, the prompt behaves correctly for SSH authentication. But if I authenticate with GitHub using personal access token (no SSH configuration at all), I will always get the prompt. Perhaps we only prompt that message if both SSH and HTTPS fail to authenticate with GitHub? Since the message is pretty generic, which works for both scenarios?

**Comment by Jelleas** [comment]
The current situation makes sense right? The prompt should always appear before asking for a PAT, because that is something that changed. Right now you see the prompt before you:

1. need to enter a passphrase
2. need to enter your GH username + PAT

**Comment by rongxin-liu** [comment]
> The current situation makes sense right? The prompt should always appear before asking for a PAT, because that is something that changed. Right now you see the prompt before you:
> 
> 1. need to enter a passphrase
> 2. need to enter your GH username + PAT

Yes, but it seems GitHub will store the PAT for a while so next time when student run check50/submit50, lib50 will not prompt for password and proceed to `verifying...`, but the prompt will still appear whenever lib50 uses https currently:

Screen Shot 2021-08-11 at 12 05 48

**Comment by Jelleas** [comment]
Alright, extracted the warning into a function that will only ever execute once. That function is called exactly before the user is prompted. All should be good now 😅

**Comment by Jelleas** [comment]
Fyi, if you're wondering why checks failed at the time of push:

image

Re-running at later stage should give all green.

**Review by rongxin-liu — CHANGES_REQUESTED** [review]
One final case, when a student is using PAT and the authentication passed, but the student answer `no` for the honesty prompt and we will see another prompt:

Screen Shot 2021-08-11 at 20 25 48

This is probably caused by the `No files were submitted` exception in the `Exception` clause in `_authenticate_https()`. Though we might eventually get rid of all these prompts, could we perhaps add a check in the exception clause so that we don't prompt message if no files were submitted? 

The other use cases all working great!

**Comment by Jelleas** [comment]
Probably best to not rely on Exception messages in case of localizations and/or changes to phrasing in the future. You wouldn't expect different phrasing to break the code 😅

I've added `RejectedHonestyPromptError` to the exception hierarchy to distinct the user rejecting the honesty prompt from other `lib50.Error`s

**Review by rongxin-liu — APPROVED** [review]

**Comment by rongxin-liu** [comment]
Just tested and it worked fine. Thank you!!

**Comment by rongxin-liu** [comment]
> Fyi, if you're wondering why checks failed at the time of push:
> 
> image
> 
> Re-running at a later stage should give all green.

Will merge after GitHub's maintenance is done.

**Pull request merged**
