### PR TITLE
special characters in password fix

### PR DESCRIPTION
**Pull request by Jelleas**
Because GitHub allows non ASCII chars in passwords, make sure to encode `str` in `utf8`.

### CODE REVIEW

**Comment by dmalan** [comment]
@kzidane want to merge if all looks good?

**Comment by kzidane** [comment]
Printing `*`s and deleting characters seems to be broken since you're reading one byte at a time? https://github.com/cs50/lib50/blob/umlautfix/lib50/api.py#L677

**Comment by Jelleas** [comment]
@kzidane I can't reproduce what you're saying. I can delete characters on OS X and on Ubuntu (cs50/baseimage), and the printed `*` disappear/appear accordingly. 

Mind that this is not new, we also read 1 byte at a time in [v2](https://github.com/cs50/submit50/blob/65a76729cbad106c4b6027d74d7721d1f874de81/submit50.py#L59) and as far as I know that works.

**Comment by kzidane** [comment]
@Jelleas my GIF recorder is broken atm but I probably should've been more clear earlier. I was talking about multibyte UTF-8 characters (e.g., Ü). I think it's a bit different in v2 since you guys seem to be using a [str](https://github.com/cs50/submit50/blob/65a76729cbad106c4b6027d74d7721d1f874de81/submit50.py#L187) while in `lib50` you seem to be using a [byte array](https://github.com/cs50/lib50/blob/941767f6c0a3b81af0cdea48c25c8d5a761086eb/lib50/_api.py#L720)?

This also seems to be causing a problem when deleting a character since you guys seem to be removing an element from the end of the array and while that's fine for a `str` in v2 since it removes a character regardless of how many bytes it takes, it's not necessarily valid with a byte array?

**Comment by Jelleas** [comment]
@kzidane ah that makes sense!

I just implemented a fix and simultaneously added some unittests to cover this usecase. Please do take a look :)

**Comment by dmalan** [comment]
@kzidane how's this now look?

**Comment by crossroads1112** [comment]
fixed in develop

**Pull request closed without merging**
